# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sandbox_pb2 as sandbox__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteCode = channel.unary_unary(
                '/sandbox.SandboxService/ExecuteCode',
                request_serializer=sandbox__pb2.ExecutionRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ExecutionResponse.FromString,
                _registered_method=True)
        self.StreamExecution = channel.stream_stream(
                '/sandbox.SandboxService/StreamExecution',
                request_serializer=sandbox__pb2.ExecutionRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ExecutionChunk.FromString,
                _registered_method=True)
        self.AnalyzeCode = channel.unary_unary(
                '/sandbox.SandboxService/AnalyzeCode',
                request_serializer=sandbox__pb2.AiAnalysisRequest.SerializeToString,
                response_deserializer=sandbox__pb2.AiAnalysisResponse.FromString,
                _registered_method=True)
        self.SearchPackages = channel.unary_unary(
                '/sandbox.SandboxService/SearchPackages',
                request_serializer=sandbox__pb2.PackageSearchRequest.SerializeToString,
                response_deserializer=sandbox__pb2.PackageSearchResponse.FromString,
                _registered_method=True)
        self.GetLanguages = channel.unary_unary(
                '/sandbox.SandboxService/GetLanguages',
                request_serializer=sandbox__pb2.Empty.SerializeToString,
                response_deserializer=sandbox__pb2.LanguagesResponse.FromString,
                _registered_method=True)


class SandboxServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ExecuteCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamExecution(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPackages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLanguages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCode,
                    request_deserializer=sandbox__pb2.ExecutionRequest.FromString,
                    response_serializer=sandbox__pb2.ExecutionResponse.SerializeToString,
            ),
            'StreamExecution': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamExecution,
                    request_deserializer=sandbox__pb2.ExecutionRequest.FromString,
                    response_serializer=sandbox__pb2.ExecutionChunk.SerializeToString,
            ),
            'AnalyzeCode': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeCode,
                    request_deserializer=sandbox__pb2.AiAnalysisRequest.FromString,
                    response_serializer=sandbox__pb2.AiAnalysisResponse.SerializeToString,
            ),
            'SearchPackages': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPackages,
                    request_deserializer=sandbox__pb2.PackageSearchRequest.FromString,
                    response_serializer=sandbox__pb2.PackageSearchResponse.SerializeToString,
            ),
            'GetLanguages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLanguages,
                    request_deserializer=sandbox__pb2.Empty.FromString,
                    response_serializer=sandbox__pb2.LanguagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sandbox.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sandbox.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/ExecuteCode',
            sandbox__pb2.ExecutionRequest.SerializeToString,
            sandbox__pb2.ExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamExecution(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sandbox.SandboxService/StreamExecution',
            sandbox__pb2.ExecutionRequest.SerializeToString,
            sandbox__pb2.ExecutionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/AnalyzeCode',
            sandbox__pb2.AiAnalysisRequest.SerializeToString,
            sandbox__pb2.AiAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPackages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/SearchPackages',
            sandbox__pb2.PackageSearchRequest.SerializeToString,
            sandbox__pb2.PackageSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLanguages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/GetLanguages',
            sandbox__pb2.Empty.SerializeToString,
            sandbox__pb2.LanguagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
