// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: ai.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

type LanguageDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageDescriptor) Reset() {
	*x = LanguageDescriptor{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageDescriptor) ProtoMessage() {}

func (x *LanguageDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageDescriptor.ProtoReflect.Descriptor instead.
func (*LanguageDescriptor) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *LanguageDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LanguageDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type LanguagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Languages     []*LanguageDescriptor  `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguagesResponse) Reset() {
	*x = LanguagesResponse{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguagesResponse) ProtoMessage() {}

func (x *LanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguagesResponse.ProtoReflect.Descriptor instead.
func (*LanguagesResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *LanguagesResponse) GetLanguages() []*LanguageDescriptor {
	if x != nil {
		return x.Languages
	}
	return nil
}

type AiAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiAnalysisRequest) Reset() {
	*x = AiAnalysisRequest{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiAnalysisRequest) ProtoMessage() {}

func (x *AiAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiAnalysisRequest.ProtoReflect.Descriptor instead.
func (*AiAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *AiAnalysisRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AiAnalysisRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AiAnalysisRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AiAnalysisRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AiAnalysisRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type AiAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Explanation   string                 `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Suggestions   []string               `protobuf:"bytes,4,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	GeneratedCode string                 `protobuf:"bytes,5,opt,name=generated_code,json=generatedCode,proto3" json:"generated_code,omitempty"`
	Provider      string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiAnalysisResponse) Reset() {
	*x = AiAnalysisResponse{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiAnalysisResponse) ProtoMessage() {}

func (x *AiAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiAnalysisResponse.ProtoReflect.Descriptor instead.
func (*AiAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *AiAnalysisResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AiAnalysisResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AiAnalysisResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *AiAnalysisResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *AiAnalysisResponse) GetGeneratedCode() string {
	if x != nil {
		return x.GeneratedCode
	}
	return ""
}

func (x *AiAnalysisResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\"\a\n" +
	"\x05Empty\"K\n" +
	"\x12LanguageDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"I\n" +
	"\x11LanguagesResponse\x124\n" +
	"\tlanguages\x18\x01 \x03(\v2\x16.ai.LanguageDescriptorR\tlanguages\"\x89\x01\n" +
	"\x11AiAnalysisRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"\xcf\x01\n" +
	"\x12AiAnalysisResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation\x12 \n" +
	"\vsuggestions\x18\x04 \x03(\tR\vsuggestions\x12%\n" +
	"\x0egenerated_code\x18\x05 \x01(\tR\rgeneratedCode\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider2{\n" +
	"\tAIService\x120\n" +
	"\fGetLanguages\x12\t.ai.Empty\x1a\x15.ai.LanguagesResponse\x12<\n" +
	"\vAnalyzeCode\x12\x15.ai.AiAnalysisRequest\x1a\x16.ai.AiAnalysisResponseB)Z'github.com/livesync/livesync-gateway/pbb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ai_proto_goTypes = []any{
	(*Empty)(nil),              // 0: ai.Empty
	(*LanguageDescriptor)(nil), // 1: ai.LanguageDescriptor
	(*LanguagesResponse)(nil),  // 2: ai.LanguagesResponse
	(*AiAnalysisRequest)(nil),  // 3: ai.AiAnalysisRequest
	(*AiAnalysisResponse)(nil), // 4: ai.AiAnalysisResponse
}
var file_ai_proto_depIdxs = []int32{
	1, // 0: ai.LanguagesResponse.languages:type_name -> ai.LanguageDescriptor
	0, // 1: ai.AIService.GetLanguages:input_type -> ai.Empty
	3, // 2: ai.AIService.AnalyzeCode:input_type -> ai.AiAnalysisRequest
	2, // 3: ai.AIService.GetLanguages:output_type -> ai.LanguagesResponse
	4, // 4: ai.AIService.AnalyzeCode:output_type -> ai.AiAnalysisResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
