// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandbox.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

type ExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	StandardInput string                 `protobuf:"bytes,3,opt,name=standard_input,json=standardInput,proto3" json:"standard_input,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"` // "start", "stdin", "kill"
	Files         map[string]string      `protobuf:"bytes,6,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Entrypoint    string                 `protobuf:"bytes,7,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecutionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecutionRequest) GetStandardInput() string {
	if x != nil {
		return x.StandardInput
	}
	return ""
}

func (x *ExecutionRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecutionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecutionRequest) GetFiles() map[string]string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ExecutionRequest) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

type ExecutionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Language        string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	IsSuccess       bool                   `protobuf:"varint,3,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ExitCode        int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout          string                 `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr          string                 `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,8,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionResponse) Reset() {
	*x = ExecutionResponse{}
	mi := &file_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResponse) ProtoMessage() {}

func (x *ExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResponse.ProtoReflect.Descriptor instead.
func (*ExecutionResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecutionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *ExecutionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecutionResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecutionResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecutionResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

type ExecutionChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamType    string                 `protobuf:"bytes,1,opt,name=stream_type,json=streamType,proto3" json:"stream_type,omitempty"` // "stdout", "stderr", "waiting_input", "exit", "status"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	RequiresInput bool                   `protobuf:"varint,3,opt,name=requires_input,json=requiresInput,proto3" json:"requires_input,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionChunk) Reset() {
	*x = ExecutionChunk{}
	mi := &file_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionChunk) ProtoMessage() {}

func (x *ExecutionChunk) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionChunk.ProtoReflect.Descriptor instead.
func (*ExecutionChunk) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionChunk) GetStreamType() string {
	if x != nil {
		return x.StreamType
	}
	return ""
}

func (x *ExecutionChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExecutionChunk) GetRequiresInput() bool {
	if x != nil {
		return x.RequiresInput
	}
	return false
}

func (x *ExecutionChunk) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ExecutionChunk) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecutionChunk) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LanguageDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageDescriptor) Reset() {
	*x = LanguageDescriptor{}
	mi := &file_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageDescriptor) ProtoMessage() {}

func (x *LanguageDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageDescriptor.ProtoReflect.Descriptor instead.
func (*LanguageDescriptor) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *LanguageDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LanguageDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type LanguagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Languages     []*LanguageDescriptor  `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguagesResponse) Reset() {
	*x = LanguagesResponse{}
	mi := &file_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguagesResponse) ProtoMessage() {}

func (x *LanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguagesResponse.ProtoReflect.Descriptor instead.
func (*LanguagesResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *LanguagesResponse) GetLanguages() []*LanguageDescriptor {
	if x != nil {
		return x.Languages
	}
	return nil
}

type AiAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiAnalysisRequest) Reset() {
	*x = AiAnalysisRequest{}
	mi := &file_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiAnalysisRequest) ProtoMessage() {}

func (x *AiAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiAnalysisRequest.ProtoReflect.Descriptor instead.
func (*AiAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *AiAnalysisRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AiAnalysisRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AiAnalysisRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AiAnalysisRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AiAnalysisRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type AiAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Explanation   string                 `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Suggestions   []string               `protobuf:"bytes,4,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	GeneratedCode string                 `protobuf:"bytes,5,opt,name=generated_code,json=generatedCode,proto3" json:"generated_code,omitempty"`
	Provider      string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiAnalysisResponse) Reset() {
	*x = AiAnalysisResponse{}
	mi := &file_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiAnalysisResponse) ProtoMessage() {}

func (x *AiAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiAnalysisResponse.ProtoReflect.Descriptor instead.
func (*AiAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *AiAnalysisResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AiAnalysisResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AiAnalysisResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *AiAnalysisResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *AiAnalysisResponse) GetGeneratedCode() string {
	if x != nil {
		return x.GeneratedCode
	}
	return ""
}

func (x *AiAnalysisResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type PackageSearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PackageManager string                 `protobuf:"bytes,1,opt,name=package_manager,json=packageManager,proto3" json:"package_manager,omitempty"` // "pypi" or "npm"
	Query          string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PackageSearchRequest) Reset() {
	*x = PackageSearchRequest{}
	mi := &file_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageSearchRequest) ProtoMessage() {}

func (x *PackageSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageSearchRequest.ProtoReflect.Descriptor instead.
func (*PackageSearchRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *PackageSearchRequest) GetPackageManager() string {
	if x != nil {
		return x.PackageManager
	}
	return ""
}

func (x *PackageSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type PackageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageItem) Reset() {
	*x = PackageItem{}
	mi := &file_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageItem) ProtoMessage() {}

func (x *PackageItem) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageItem.ProtoReflect.Descriptor instead.
func (*PackageItem) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *PackageItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageItem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackageItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PackageSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Packages      []*PackageItem         `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageSearchResponse) Reset() {
	*x = PackageSearchResponse{}
	mi := &file_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageSearchResponse) ProtoMessage() {}

func (x *PackageSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageSearchResponse.ProtoReflect.Descriptor instead.
func (*PackageSearchResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *PackageSearchResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PackageSearchResponse) GetPackages() []*PackageItem {
	if x != nil {
		return x.Packages
	}
	return nil
}

var File_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_proto_rawDesc = "" +
	"\n" +
	"\rsandbox.proto\x12\asandbox\"\a\n" +
	"\x05Empty\"\xb6\x02\n" +
	"\x10ExecutionRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12%\n" +
	"\x0estandard_input\x18\x03 \x01(\tR\rstandardInput\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12:\n" +
	"\x05files\x18\x06 \x03(\v2$.sandbox.ExecutionRequest.FilesEntryR\x05files\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\a \x01(\tR\n" +
	"entrypoint\x1a8\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\x11ExecutionResponse\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"is_success\x18\x03 \x01(\bR\tisSuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr\x12*\n" +
	"\x11execution_time_ms\x18\b \x01(\x03R\x0fexecutionTimeMs\"\xbf\x01\n" +
	"\x0eExecutionChunk\x12\x1f\n" +
	"\vstream_type\x18\x01 \x01(\tR\n" +
	"streamType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12%\n" +
	"\x0erequires_input\x18\x03 \x01(\bR\rrequiresInput\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"K\n" +
	"\x12LanguageDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"N\n" +
	"\x11LanguagesResponse\x129\n" +
	"\tlanguages\x18\x01 \x03(\v2\x1b.sandbox.LanguageDescriptorR\tlanguages\"\x89\x01\n" +
	"\x11AiAnalysisRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"\xcf\x01\n" +
	"\x12AiAnalysisResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation\x12 \n" +
	"\vsuggestions\x18\x04 \x03(\tR\vsuggestions\x12%\n" +
	"\x0egenerated_code\x18\x05 \x01(\tR\rgeneratedCode\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\"U\n" +
	"\x14PackageSearchRequest\x12'\n" +
	"\x0fpackage_manager\x18\x01 \x01(\tR\x0epackageManager\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"]\n" +
	"\vPackageItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"_\n" +
	"\x15PackageSearchResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x120\n" +
	"\bpackages\x18\x02 \x03(\v2\x14.sandbox.PackageItemR\bpackages2\xf6\x02\n" +
	"\x0eSandboxService\x12D\n" +
	"\vExecuteCode\x12\x19.sandbox.ExecutionRequest\x1a\x1a.sandbox.ExecutionResponse\x12I\n" +
	"\x0fStreamExecution\x12\x19.sandbox.ExecutionRequest\x1a\x17.sandbox.ExecutionChunk(\x010\x01\x12F\n" +
	"\vAnalyzeCode\x12\x1a.sandbox.AiAnalysisRequest\x1a\x1b.sandbox.AiAnalysisResponse\x12O\n" +
	"\x0eSearchPackages\x12\x1d.sandbox.PackageSearchRequest\x1a\x1e.sandbox.PackageSearchResponse\x12:\n" +
	"\fGetLanguages\x12\x0e.sandbox.Empty\x1a\x1a.sandbox.LanguagesResponseB)Z'github.com/livesync/livesync-gateway/pbb\x06proto3"

var (
	file_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_proto_rawDescData []byte
)

func file_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)))
	})
	return file_sandbox_proto_rawDescData
}

var file_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sandbox_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: sandbox.Empty
	(*ExecutionRequest)(nil),      // 1: sandbox.ExecutionRequest
	(*ExecutionResponse)(nil),     // 2: sandbox.ExecutionResponse
	(*ExecutionChunk)(nil),        // 3: sandbox.ExecutionChunk
	(*LanguageDescriptor)(nil),    // 4: sandbox.LanguageDescriptor
	(*LanguagesResponse)(nil),     // 5: sandbox.LanguagesResponse
	(*AiAnalysisRequest)(nil),     // 6: sandbox.AiAnalysisRequest
	(*AiAnalysisResponse)(nil),    // 7: sandbox.AiAnalysisResponse
	(*PackageSearchRequest)(nil),  // 8: sandbox.PackageSearchRequest
	(*PackageItem)(nil),           // 9: sandbox.PackageItem
	(*PackageSearchResponse)(nil), // 10: sandbox.PackageSearchResponse
	nil,                           // 11: sandbox.ExecutionRequest.FilesEntry
}
var file_sandbox_proto_depIdxs = []int32{
	11, // 0: sandbox.ExecutionRequest.files:type_name -> sandbox.ExecutionRequest.FilesEntry
	4,  // 1: sandbox.LanguagesResponse.languages:type_name -> sandbox.LanguageDescriptor
	9,  // 2: sandbox.PackageSearchResponse.packages:type_name -> sandbox.PackageItem
	1,  // 3: sandbox.SandboxService.ExecuteCode:input_type -> sandbox.ExecutionRequest
	1,  // 4: sandbox.SandboxService.StreamExecution:input_type -> sandbox.ExecutionRequest
	6,  // 5: sandbox.SandboxService.AnalyzeCode:input_type -> sandbox.AiAnalysisRequest
	8,  // 6: sandbox.SandboxService.SearchPackages:input_type -> sandbox.PackageSearchRequest
	0,  // 7: sandbox.SandboxService.GetLanguages:input_type -> sandbox.Empty
	2,  // 8: sandbox.SandboxService.ExecuteCode:output_type -> sandbox.ExecutionResponse
	3,  // 9: sandbox.SandboxService.StreamExecution:output_type -> sandbox.ExecutionChunk
	7,  // 10: sandbox.SandboxService.AnalyzeCode:output_type -> sandbox.AiAnalysisResponse
	10, // 11: sandbox.SandboxService.SearchPackages:output_type -> sandbox.PackageSearchResponse
	5,  // 12: sandbox.SandboxService.GetLanguages:output_type -> sandbox.LanguagesResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_sandbox_proto_init() }
func file_sandbox_proto_init() {
	if File_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_proto_depIdxs,
		MessageInfos:      file_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_proto = out.File
	file_sandbox_proto_goTypes = nil
	file_sandbox_proto_depIdxs = nil
}
