// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: sandbox.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxService_ExecuteCode_FullMethodName     = "/sandbox.SandboxService/ExecuteCode"
	SandboxService_StreamExecution_FullMethodName = "/sandbox.SandboxService/StreamExecution"
	SandboxService_AnalyzeCode_FullMethodName     = "/sandbox.SandboxService/AnalyzeCode"
	SandboxService_SearchPackages_FullMethodName  = "/sandbox.SandboxService/SearchPackages"
	SandboxService_GetLanguages_FullMethodName    = "/sandbox.SandboxService/GetLanguages"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandboxServiceClient interface {
	ExecuteCode(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error)
	StreamExecution(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecutionChunk], error)
	AnalyzeCode(ctx context.Context, in *AiAnalysisRequest, opts ...grpc.CallOption) (*AiAnalysisResponse, error)
	SearchPackages(ctx context.Context, in *PackageSearchRequest, opts ...grpc.CallOption) (*PackageSearchResponse, error)
	GetLanguages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LanguagesResponse, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) ExecuteCode(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResponse)
	err := c.cc.Invoke(ctx, SandboxService_ExecuteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) StreamExecution(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecutionChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxService_ServiceDesc.Streams[0], SandboxService_StreamExecution_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecutionRequest, ExecutionChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_StreamExecutionClient = grpc.ServerStreamingClient[ExecutionChunk]

func (c *sandboxServiceClient) AnalyzeCode(ctx context.Context, in *AiAnalysisRequest, opts ...grpc.CallOption) (*AiAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AiAnalysisResponse)
	err := c.cc.Invoke(ctx, SandboxService_AnalyzeCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SearchPackages(ctx context.Context, in *PackageSearchRequest, opts ...grpc.CallOption) (*PackageSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageSearchResponse)
	err := c.cc.Invoke(ctx, SandboxService_SearchPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) GetLanguages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LanguagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LanguagesResponse)
	err := c.cc.Invoke(ctx, SandboxService_GetLanguages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility.
type SandboxServiceServer interface {
	ExecuteCode(context.Context, *ExecutionRequest) (*ExecutionResponse, error)
	StreamExecution(*ExecutionRequest, grpc.ServerStreamingServer[ExecutionChunk]) error
	AnalyzeCode(context.Context, *AiAnalysisRequest) (*AiAnalysisResponse, error)
	SearchPackages(context.Context, *PackageSearchRequest) (*PackageSearchResponse, error)
	GetLanguages(context.Context, *Empty) (*LanguagesResponse, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServiceServer struct{}

func (UnimplementedSandboxServiceServer) ExecuteCode(context.Context, *ExecutionRequest) (*ExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCode not implemented")
}
func (UnimplementedSandboxServiceServer) StreamExecution(*ExecutionRequest, grpc.ServerStreamingServer[ExecutionChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamExecution not implemented")
}
func (UnimplementedSandboxServiceServer) AnalyzeCode(context.Context, *AiAnalysisRequest) (*AiAnalysisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeCode not implemented")
}
func (UnimplementedSandboxServiceServer) SearchPackages(context.Context, *PackageSearchRequest) (*PackageSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchPackages not implemented")
}
func (UnimplementedSandboxServiceServer) GetLanguages(context.Context, *Empty) (*LanguagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLanguages not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}
func (UnimplementedSandboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	// If the following call panics, it indicates UnimplementedSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_ExecuteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ExecuteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ExecuteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ExecuteCode(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_StreamExecution_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecutionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServiceServer).StreamExecution(m, &grpc.GenericServerStream[ExecutionRequest, ExecutionChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_StreamExecutionServer = grpc.ServerStreamingServer[ExecutionChunk]

func _SandboxService_AnalyzeCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AiAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).AnalyzeCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_AnalyzeCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).AnalyzeCode(ctx, req.(*AiAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SearchPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SearchPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SearchPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SearchPackages(ctx, req.(*PackageSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_GetLanguages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).GetLanguages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_GetLanguages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).GetLanguages(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCode",
			Handler:    _SandboxService_ExecuteCode_Handler,
		},
		{
			MethodName: "AnalyzeCode",
			Handler:    _SandboxService_AnalyzeCode_Handler,
		},
		{
			MethodName: "SearchPackages",
			Handler:    _SandboxService_SearchPackages_Handler,
		},
		{
			MethodName: "GetLanguages",
			Handler:    _SandboxService_GetLanguages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamExecution",
			Handler:       _SandboxService_StreamExecution_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sandbox.proto",
}
