global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'livesync-sandbox'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['livesync-sandbox:8080']

  - job_name: 'livesync-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['livesync-api:8080']
