# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import ai_pb2 as ai__pb2
except ImportError:
    import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLanguages = channel.unary_unary(
                '/ai.AIService/GetLanguages',
                request_serializer=ai__pb2.Empty.SerializeToString,
                response_deserializer=ai__pb2.LanguagesResponse.FromString,
                _registered_method=True)
        self.AnalyzeCode = channel.unary_unary(
                '/ai.AIService/AnalyzeCode',
                request_serializer=ai__pb2.AiAnalysisRequest.SerializeToString,
                response_deserializer=ai__pb2.AiAnalysisResponse.FromString,
                _registered_method=True)
        self.StreamAnalyzeCode = channel.unary_stream(
                '/ai.AIService/StreamAnalyzeCode',
                request_serializer=ai__pb2.AiAnalysisRequest.SerializeToString,
                response_deserializer=ai__pb2.AiAnalysisChunk.FromString,
                _registered_method=True)


class AIServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetLanguages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAnalyzeCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLanguages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLanguages,
                    request_deserializer=ai__pb2.Empty.FromString,
                    response_serializer=ai__pb2.LanguagesResponse.SerializeToString,
            ),
            'AnalyzeCode': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeCode,
                    request_deserializer=ai__pb2.AiAnalysisRequest.FromString,
                    response_serializer=ai__pb2.AiAnalysisResponse.SerializeToString,
            ),
            'StreamAnalyzeCode': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAnalyzeCode,
                    request_deserializer=ai__pb2.AiAnalysisRequest.FromString,
                    response_serializer=ai__pb2.AiAnalysisChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLanguages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/GetLanguages',
            ai__pb2.Empty.SerializeToString,
            ai__pb2.LanguagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/AnalyzeCode',
            ai__pb2.AiAnalysisRequest.SerializeToString,
            ai__pb2.AiAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAnalyzeCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.AIService/StreamAnalyzeCode',
            ai__pb2.AiAnalysisRequest.SerializeToString,
            ai__pb2.AiAnalysisChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
